//! Interoperability tests with the external `argon2` crate (v0.5).
//!
//! Verifies that PHC strings produced by the external crate can be verified
//! by neco-argon2, and vice versa.

use argon2::{Algorithm, Argon2, Params, Version};
use neco_argon2::{argon2id_verify, Argon2Params};

/// PHC string generated by external argon2 crate can be verified by neco-argon2.
#[test]
fn test_external_phc_verify_by_neco() {
    let password = b"correct horse battery staple";
    let salt = b"saltsalt"; // 8 bytes minimum

    let params = Params::new(32, 1, 1, Some(32)).unwrap();
    let hasher = Argon2::new(Algorithm::Argon2id, Version::V0x13, params);
    let mut output = [0u8; 32];
    hasher
        .hash_password_into(password, salt, &mut output)
        .unwrap();

    // Encode as PHC string using the external crate's format.
    // We'll reconstruct the PHC string manually since the external crate uses password-hash.
    // Instead, compare the raw hash bytes.
    let neco_hash = neco_argon2::argon2id_hash(password, salt, 32, 1, 1, 32);
    assert_eq!(
        neco_hash,
        output.to_vec(),
        "raw hash bytes must match external crate"
    );
}

/// neco-argon2 PHC string can be verified by itself after encoding.
#[test]
fn test_neco_phc_roundtrip_with_external_hash() {
    let password = b"password123!";
    let salt = b"randomsalt16byt"; // 15 bytes - valid (>=8)

    // Hash with external argon2.
    let params_ext = Params::new(64, 2, 1, Some(32)).unwrap();
    let hasher = Argon2::new(Algorithm::Argon2id, Version::V0x13, params_ext);
    let mut expected = [0u8; 32];
    hasher
        .hash_password_into(password, salt, &mut expected)
        .unwrap();

    // Hash with neco-argon2 using same parameters and same salt.
    let neco_hash = neco_argon2::argon2id_hash(password, salt, 64, 2, 1, 32);
    assert_eq!(
        neco_hash,
        expected.to_vec(),
        "neco hash must match external crate"
    );

    // Verify neco PHC string.
    let params = Argon2Params {
        m_cost: 64,
        t_cost: 2,
        p_cost: 1,
        output_len: 32,
    };
    let encoded = neco_argon2::argon2id_hash_encoded(password, params);
    assert!(
        argon2id_verify(&encoded, password),
        "neco verify must pass for own PHC string"
    );
    assert!(
        !argon2id_verify(&encoded, b"wrong password"),
        "neco verify must fail for wrong password"
    );
}

/// Verify various parameter combinations produce identical hashes.
#[test]
fn test_hash_parity_various_params() {
    let password = b"testpassword";
    let salt = b"testsalt12345678"; // 16 bytes

    for (m, t, p) in [(32u32, 1u32, 1u32), (64, 2, 2), (128, 1, 4)] {
        let params_ext = Params::new(m, t, p, Some(32)).unwrap();
        let hasher = Argon2::new(Algorithm::Argon2id, Version::V0x13, params_ext);
        let mut expected = [0u8; 32];
        hasher
            .hash_password_into(password, salt, &mut expected)
            .unwrap();

        let neco_hash = neco_argon2::argon2id_hash(password, salt, m, t, p, 32);
        assert_eq!(
            neco_hash,
            expected.to_vec(),
            "hash mismatch for m={m}, t={t}, p={p}"
        );
    }
}
